import { ChoosePredicateTypeModal } from './choosePredicateTypeModal';
import { CopyPredicateModal } from './copyPredicateModal';
import { SearchConceptModal } from './searchConceptModal';
import { SearchClassModal } from './searchClassModal';
import { SearchPredicateModal } from './searchPredicateModal';
import { AddPropertiesFromClassModal } from './addPropertiesFromClassModal';
import { ClassFormComponent } from './classForm';
import { EditableMultipleComponent } from './editableMultiple';
import { ClassViewComponent } from './classView';
import { PredicateViewComponent } from './predicateView';
import { DefinedByComponent } from './definedBy';
import { UriSelectComponent } from './uriSelect';
import { EditableConstraintComponent } from './editableConstraint';
import { EditableMultipleUriSelectComponent } from './editableMultipleUriSelect';
import { EditableMultipleDataTypeInputComponent } from './editableMultipleDataTypeInput';
import { EditableMultipleLanguageSelectComponent } from './editableMultipleLanguageSelect';
import { EditableReferenceDataSelectComponent } from './editableReferenceDataSelect';
import { PredicateFormComponent } from './predicateForm';
import { PropertyViewComponent } from './propertyView';
import { PropertyPredicateViewComponent } from './propertyPredicateView';
import { EditableRangeSelectComponent } from './editableRangeSelect';
import { SelectionViewComponent } from './selectionView';
import { SubjectViewComponent } from './subjectView';
import { VisualizationViewComponent } from './visualizationView';

import { registerComponent } from 'app/utils/angular';
import { module as mod } from './module';
export { module } from './module';

registerComponent(mod, ClassFormComponent);
registerComponent(mod, ClassViewComponent);
registerComponent(mod, DefinedByComponent);
registerComponent(mod, UriSelectComponent);
registerComponent(mod, EditableConstraintComponent);
registerComponent(mod, EditableMultipleComponent);
registerComponent(mod, EditableMultipleUriSelectComponent);
registerComponent(mod, EditableMultipleDataTypeInputComponent);
registerComponent(mod, EditableMultipleLanguageSelectComponent);
registerComponent(mod, EditableReferenceDataSelectComponent);
registerComponent(mod, PredicateFormComponent);
registerComponent(mod, PredicateViewComponent);
registerComponent(mod, PropertyViewComponent);
registerComponent(mod, PropertyPredicateViewComponent);
registerComponent(mod, EditableRangeSelectComponent);
registerComponent(mod, SelectionViewComponent);
registerComponent(mod, SubjectViewComponent);
registerComponent(mod, VisualizationViewComponent);

mod.service('choosePredicateTypeModal', ChoosePredicateTypeModal);
mod.service('copyPredicateModal', CopyPredicateModal);
mod.service('addPropertiesFromClassModal', AddPropertiesFromClassModal);
mod.service('searchClassModal', SearchClassModal);
mod.service('searchConceptModal', SearchConceptModal);
mod.service('searchPredicateModal', SearchPredicateModal);
