import { SearchNamespaceModal } from './searchNamespaceModal';
import { SearchVocabularyModal } from './searchVocabularyModal';
import { AddEditLinkModal } from './addEditLinkModal';
import { AddEditNamespaceModal } from './addEditNamespaceModal';
import { SearchReferenceDataModal } from './searchReferenceDataModal';
import { EditReferenceDataModal } from './editReferenceDataModal';
import { ViewReferenceDataModal} from './viewReferenceDataModal';
import { SearchClassificationModal } from './searchClassificationModal';
import { SearchOrganizationModal } from './searchOrganizationModal';
import { ModelFormComponent } from './modelForm';
import { ModelViewComponent } from './modelView';
import { ClassificationsViewComponent } from './classificationsView';
import { VocabulariesViewComponent } from './vocabulariesView';
import { ImportedNamespacesViewComponent } from './importedNamespacesView';
import { LinksViewComponent } from './linksView';
import { ReferenceDataViewComponent } from './referenceDataView';
import { ReferenceDatasViewComponent } from './referenceDatasView';
import { TechnicalNamespacesComponent } from './technicalNamespaces';
import { ContributosViewComponent } from './contributorsView';
import { DividerComponent } from './divider';
import { EditableRootClassCompoonent } from './editableRootClass';
import { ConceptFormComponent } from './conceptForm';
import { ModelPageComponent } from './modelPage';
import { NewModelPageComponent } from './newModelPage';
import { NonEditableVocabularyComponent } from './nonEditableVocabulary';

import { registerComponent } from 'app/utils/angular';
import { module as mod } from './module';
export { module } from './module';

registerComponent(mod, EditableRootClassCompoonent);
registerComponent(mod, ConceptFormComponent);
registerComponent(mod, DividerComponent);
registerComponent(mod, ModelPageComponent);
registerComponent(mod, NewModelPageComponent);
registerComponent(mod, ModelFormComponent);
registerComponent(mod, ModelViewComponent);
registerComponent(mod, NonEditableVocabularyComponent);
registerComponent(mod, VocabulariesViewComponent);
registerComponent(mod, ImportedNamespacesViewComponent);
registerComponent(mod, LinksViewComponent);
registerComponent(mod, ReferenceDataViewComponent);
registerComponent(mod, ReferenceDatasViewComponent);
registerComponent(mod, TechnicalNamespacesComponent);
registerComponent(mod, ClassificationsViewComponent);
registerComponent(mod, ContributosViewComponent);

mod.service('addEditLinkModal', AddEditLinkModal);
mod.service('addEditNamespaceModal', AddEditNamespaceModal);
mod.service('searchNamespaceModal', SearchNamespaceModal);
mod.service('searchVocabularyModal', SearchVocabularyModal);
mod.service('searchReferenceDataModal', SearchReferenceDataModal);
mod.service('editReferenceDataModal', EditReferenceDataModal);
mod.service('viewReferenceDataModal', ViewReferenceDataModal);
mod.service('searchClassificationModal', SearchClassificationModal);
mod.service('searchOrganizationModal', SearchOrganizationModal);
