import { ErrorModal } from './errorModal';
import { DisplayItemFactory } from './displayItemFactory';
import { InputPopupComponent, InputPopupItemTranscludeDirective, InputPopupSelectItemDirective } from './inputPopup';
import { ErrorMessagesComponent } from './errorMessages';
import { NonEditableComponent } from './nonEditable';
import { EditableLabelComponent } from './editableLabel';
import { EditableComponent } from './editable';
import { EditableStateSelectComponent } from './editableStateSelect';
import { EditableTableComponent } from './editableTable';
import { AutocompleteComponent } from './autocomplete';
import { IowSelectSelectableItemTranscludeDirective, IowSelectComponent, IowSelectInputDirective, IowSelectSelectionTranscludeDirective } from './iowSelect';
import { LocalizedSelectComponent } from './localizedSelect';
import { EditableEntityButtons } from './editableEntityButtons';
import { CodeValueInputAutocompleteComponent } from './codeValueInputAutocomplete';
import { ModelLanguageChooserComponent } from './modelLanguageChooser';
import { ErrorPanelComponent } from './errorPanel';
import { CodeValueInputDirective } from './codeValueInput';
import { ExcludeValidatorDirective } from './excludeValidator';
import { StringInputDirective } from './stringInput';
import { PrefixInputDirective } from './prefixInput';
import { NamespaceInputDirective } from './namespaceInput';
import { DataTypeInputDirective } from './dataTypeInput';
import { BootstrapInputDirective } from './bootstrapInput';
import { UriInputDirective } from './uriInput';
import { HrefDirective } from './href';
import { IdInputDirective } from './idInput';
import { LocalizedInputDirective } from './localizedInput';
import { LanguageInputDirective } from './languageInput';
import { RestrictDuplicatesDirective } from './restrictDuplicates';
import { MaxInputDirective } from './maxInput';
import { MinInputDirective } from './minInput';
import { IgnoreDirtyDirective } from './ignoreDirty';
import { IgnoreFormDirective } from './ignoreForm';
import { DragSortableDirective, DragSortableItemDirective } from './dragSortable';

import { registerComponent, registerDirective } from 'app/utils/angular';
import { module as mod } from './module';
export { module } from './module';

registerComponent(mod, AutocompleteComponent);
registerComponent(mod, CodeValueInputAutocompleteComponent);
registerComponent(mod, NonEditableComponent);
registerComponent(mod, EditableComponent);
registerComponent(mod, EditableLabelComponent);
registerComponent(mod, EditableEntityButtons);
registerComponent(mod, ErrorMessagesComponent);
registerComponent(mod, ModelLanguageChooserComponent);
registerComponent(mod, EditableStateSelectComponent);
registerComponent(mod, ErrorPanelComponent);
registerComponent(mod, EditableTableComponent);
registerComponent(mod, IowSelectComponent);
registerDirective(mod, IowSelectInputDirective);
registerDirective(mod, IowSelectSelectionTranscludeDirective);
registerDirective(mod, IowSelectSelectableItemTranscludeDirective);
registerComponent(mod, LocalizedSelectComponent);
registerComponent(mod, InputPopupComponent);
registerDirective(mod, InputPopupSelectItemDirective);
registerDirective(mod, InputPopupItemTranscludeDirective);

registerDirective(mod, CodeValueInputDirective);
registerDirective(mod, ExcludeValidatorDirective);
registerDirective(mod, StringInputDirective);
registerDirective(mod, PrefixInputDirective);
registerDirective(mod, NamespaceInputDirective);
registerDirective(mod, DataTypeInputDirective);
registerDirective(mod, BootstrapInputDirective);
registerDirective(mod, UriInputDirective);
registerDirective(mod, HrefDirective);
registerDirective(mod, IdInputDirective);
registerDirective(mod, LocalizedInputDirective);
registerDirective(mod, LanguageInputDirective);
registerDirective(mod, RestrictDuplicatesDirective);
registerDirective(mod, MaxInputDirective);
registerDirective(mod, MinInputDirective);
registerDirective(mod, IgnoreDirtyDirective);
registerDirective(mod, IgnoreFormDirective);
registerDirective(mod, DragSortableDirective);
registerDirective(mod, DragSortableItemDirective);

mod.service('errorModal', ErrorModal);
mod.service('displayItemFactory', DisplayItemFactory);
